# Deferred markets 82-87. Include only after batch one is executed and published.
###############################################################################
# Market 82 NVDA Configuration -- staged mainnet
###############################################################################
[var.market_82nvda]
market82Nvda_riskMatrixIndex = "0"
cp1Rusd_market82Nvda_riskMatrix00Unscaled = "0.023669"
market82Nvda_maxOpenBaseUnscaled = "0"
market82Nvda_oracleNodeId = "<%= settings.nvdaUsdcMarkNodeIdStork %>"
market82Nvda_dutchConfig_lambdaUnscaled = "1"
market82Nvda_dutchConfig_minBaseUnscaled = "0.04"
market82Nvda_slippageParams_phiUnscaled = "0"
market82Nvda_slippageParams_betaUnscaled = "0"
market82Nvda_minimumOrderBaseUnscaled = "0.04"
market82Nvda_baseSpacingUnscaled = "0.001"
market82Nvda_priceSpacingUnscaled = "0.01"
market82Nvda_markPriceMaxStaleDuration = "60"
market82Nvda_fundingRateMaxStaleDuration = "600"
market82Nvda_minFundingInterval = "0"
market82Nvda_markPriceMaxDeviationUnscaled = "0.05"
market82Nvda_fillPriceMaxDeviationUnscaled = "0.05"
market82Nvda_priceSpreadUnscaled = "0"
market82Nvda_volatilityIndexMultiplierUnscaled = "0"
market82Nvda_maxPSlippageUnscaled = "0"
market82Nvda_maxExposureFactorUnscaled = "0.999"
market82Nvda_depthFactorUnscaled = "0"
market82Nvda_mtmWindow = "<%= 500 * settings.ONE_YEAR_IN_SECONDS %>"
market82Nvda_velocityMultiplierUnscaled = "0"

###############################################################################
# Market 83 META Configuration -- staged mainnet
###############################################################################
[var.market_83meta]
market83Meta_riskMatrixIndex = "0"
cp1Rusd_market83Meta_riskMatrix00Unscaled = "0.06575"
market83Meta_maxOpenBaseUnscaled = "0"
market83Meta_oracleNodeId = "<%= settings.metaUsdcMarkNodeIdStork %>"
market83Meta_dutchConfig_lambdaUnscaled = "1"
market83Meta_dutchConfig_minBaseUnscaled = "0.015"
market83Meta_slippageParams_phiUnscaled = "0"
market83Meta_slippageParams_betaUnscaled = "0"
market83Meta_minimumOrderBaseUnscaled = "0.015"
market83Meta_baseSpacingUnscaled = "0.0001"
market83Meta_priceSpacingUnscaled = "0.01"
market83Meta_markPriceMaxStaleDuration = "60"
market83Meta_fundingRateMaxStaleDuration = "600"
market83Meta_minFundingInterval = "0"
market83Meta_markPriceMaxDeviationUnscaled = "0.05"
market83Meta_fillPriceMaxDeviationUnscaled = "0.05"
market83Meta_priceSpreadUnscaled = "0"
market83Meta_volatilityIndexMultiplierUnscaled = "0"
market83Meta_maxPSlippageUnscaled = "0"
market83Meta_maxExposureFactorUnscaled = "0.999"
market83Meta_depthFactorUnscaled = "0"
market83Meta_mtmWindow = "<%= 500 * settings.ONE_YEAR_IN_SECONDS %>"
market83Meta_velocityMultiplierUnscaled = "0"

###############################################################################
# Market 84 TSLA Configuration -- staged mainnet
###############################################################################
[var.market_84tsla]
market84Tsla_riskMatrixIndex = "0"
cp1Rusd_market84Tsla_riskMatrix00Unscaled = "0.023669"
market84Tsla_maxOpenBaseUnscaled = "0"
market84Tsla_oracleNodeId = "<%= settings.tslaUsdcMarkNodeIdStork %>"
market84Tsla_dutchConfig_lambdaUnscaled = "1"
market84Tsla_dutchConfig_minBaseUnscaled = "0.03"
market84Tsla_slippageParams_phiUnscaled = "0"
market84Tsla_slippageParams_betaUnscaled = "0"
market84Tsla_minimumOrderBaseUnscaled = "0.03"
market84Tsla_baseSpacingUnscaled = "0.0001"
market84Tsla_priceSpacingUnscaled = "0.01"
market84Tsla_markPriceMaxStaleDuration = "60"
market84Tsla_fundingRateMaxStaleDuration = "600"
market84Tsla_minFundingInterval = "0"
market84Tsla_markPriceMaxDeviationUnscaled = "0.05"
market84Tsla_fillPriceMaxDeviationUnscaled = "0.05"
market84Tsla_priceSpreadUnscaled = "0"
market84Tsla_volatilityIndexMultiplierUnscaled = "0"
market84Tsla_maxPSlippageUnscaled = "0"
market84Tsla_maxExposureFactorUnscaled = "0.999"
market84Tsla_depthFactorUnscaled = "0"
market84Tsla_mtmWindow = "<%= 500 * settings.ONE_YEAR_IN_SECONDS %>"
market84Tsla_velocityMultiplierUnscaled = "0"

###############################################################################
# Market 85 SPY Configuration -- staged mainnet
###############################################################################
[var.market_85spy]
market85Spy_riskMatrixIndex = "0"
cp1Rusd_market85Spy_riskMatrix00Unscaled = "0.005917"
market85Spy_maxOpenBaseUnscaled = "0"
market85Spy_oracleNodeId = "<%= settings.spyUsdcMarkNodeIdStork %>"
market85Spy_dutchConfig_lambdaUnscaled = "1"
market85Spy_dutchConfig_minBaseUnscaled = "0.015"
market85Spy_slippageParams_phiUnscaled = "0"
market85Spy_slippageParams_betaUnscaled = "0"
market85Spy_minimumOrderBaseUnscaled = "0.015"
market85Spy_baseSpacingUnscaled = "0.0001"
market85Spy_priceSpacingUnscaled = "0.01"
market85Spy_markPriceMaxStaleDuration = "60"
market85Spy_fundingRateMaxStaleDuration = "600"
market85Spy_minFundingInterval = "0"
market85Spy_markPriceMaxDeviationUnscaled = "0.05"
market85Spy_fillPriceMaxDeviationUnscaled = "0.05"
market85Spy_priceSpreadUnscaled = "0"
market85Spy_volatilityIndexMultiplierUnscaled = "0"
market85Spy_maxPSlippageUnscaled = "0"
market85Spy_maxExposureFactorUnscaled = "0.999"
market85Spy_depthFactorUnscaled = "0"
market85Spy_mtmWindow = "<%= 500 * settings.ONE_YEAR_IN_SECONDS %>"
market85Spy_velocityMultiplierUnscaled = "0"

###############################################################################
# Market 86 QQQ Configuration -- staged mainnet
###############################################################################
[var.market_86qqq]
market86Qqq_riskMatrixIndex = "0"
cp1Rusd_market86Qqq_riskMatrix00Unscaled = "0.005917"
market86Qqq_maxOpenBaseUnscaled = "0"
market86Qqq_oracleNodeId = "<%= settings.qqqUsdcMarkNodeIdStork %>"
market86Qqq_dutchConfig_lambdaUnscaled = "1"
market86Qqq_dutchConfig_minBaseUnscaled = "0.015"
market86Qqq_slippageParams_phiUnscaled = "0"
market86Qqq_slippageParams_betaUnscaled = "0"
market86Qqq_minimumOrderBaseUnscaled = "0.015"
market86Qqq_baseSpacingUnscaled = "0.0001"
market86Qqq_priceSpacingUnscaled = "0.01"
market86Qqq_markPriceMaxStaleDuration = "60"
market86Qqq_fundingRateMaxStaleDuration = "600"
market86Qqq_minFundingInterval = "0"
market86Qqq_markPriceMaxDeviationUnscaled = "0.05"
market86Qqq_fillPriceMaxDeviationUnscaled = "0.05"
market86Qqq_priceSpreadUnscaled = "0"
market86Qqq_volatilityIndexMultiplierUnscaled = "0"
market86Qqq_maxPSlippageUnscaled = "0"
market86Qqq_maxExposureFactorUnscaled = "0.999"
market86Qqq_depthFactorUnscaled = "0"
market86Qqq_mtmWindow = "<%= 500 * settings.ONE_YEAR_IN_SECONDS %>"
market86Qqq_velocityMultiplierUnscaled = "0"

###############################################################################
# Market 87 WTI Configuration -- staged mainnet
###############################################################################
[var.market_87wti]
market87Wti_riskMatrixIndex = "0"
cp1Rusd_market87Wti_riskMatrix00Unscaled = "0.023669"
market87Wti_maxOpenBaseUnscaled = "0"
market87Wti_oracleNodeId = "<%= settings.wtiUsdcMarkNodeIdStork %>"
market87Wti_dutchConfig_lambdaUnscaled = "1"
market87Wti_dutchConfig_minBaseUnscaled = "0.1"
market87Wti_slippageParams_phiUnscaled = "0"
market87Wti_slippageParams_betaUnscaled = "0"
market87Wti_minimumOrderBaseUnscaled = "0.1"
market87Wti_baseSpacingUnscaled = "0.001"
market87Wti_priceSpacingUnscaled = "0.001"
market87Wti_markPriceMaxStaleDuration = "60"
market87Wti_fundingRateMaxStaleDuration = "600"
market87Wti_minFundingInterval = "0"
market87Wti_markPriceMaxDeviationUnscaled = "0.05"
market87Wti_fillPriceMaxDeviationUnscaled = "0.05"
market87Wti_priceSpreadUnscaled = "0"
market87Wti_volatilityIndexMultiplierUnscaled = "0"
market87Wti_maxPSlippageUnscaled = "0"
market87Wti_maxExposureFactorUnscaled = "0.999"
market87Wti_depthFactorUnscaled = "0"
market87Wti_mtmWindow = "<%= 500 * settings.ONE_YEAR_IN_SECONDS %>"
market87Wti_velocityMultiplierUnscaled = "0"
