include = ["../../passive_perp/configs/global_config.toml"]

[var.perpob_global_tombstones]
perpExchangeTombstone = "<%= AddressZero %>"
perpOracleManagerTombstone = "<%= imports.reyaOracleManagerProxy.contracts.InitialProxy.address %>"
